name: Deploy to gh-pages

on:
  push:
    branches: main

jobs:
  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: mkdir out
      - name: Build HTML  
      - name: Build Pandoc
        uses: docker://pandoc/core:2.11
        with:
          args: -d pandoc/pandoc -t html5 -o out/index.html -B pandoc/html-prefix.md
      - name: Build PDF
        uses: docker://pandoc/latex:2.11
        with:
          args: -d pandoc/pandoc -t pdf -o out/proposal.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
        
